name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull the code from your repo onto the runner
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: List files to PROVE the robot can see your code
      - name: List files in repo
        run: ls -R