name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull the code from your repo onto the runner
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: List files to PROVE the robot can see your code
      - name: List files in repo
        run: ls -R

      # Step 3: Install Python on the runner
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 4: Install the libraries from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run tests
      - name: Run tests with pytest
        run: pytest

      # Step 6: Lint code with flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  test-secrets:
      runs-on: ubuntu-latest
      steps:
        - name: Try to reveal the secret
          env:
            THE_SECRET: ${{ secrets.MY_NICKNAME }}
          run: |
            echo "My nickname is $THE_SECRET"